services:
  web:
    image: yogeshv2005/verification-system:latest
    build: .
    container_name: zkp_flask_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
    env_file:
      - .env